// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/RetroPolkaDotBirthdayInvite-tajENT/KidsInvite.tsx": () => import("../components/mockups/templates/RetroPolkaDotBirthdayInvite-tajENT/KidsInvite.tsx"),
  "./components/mockups/templates/SustainableFashionLandingPage-YEy2Gd/Lp08.tsx": () => import("../components/mockups/templates/SustainableFashionLandingPage-YEy2Gd/Lp08.tsx")
};
